#tomcat
server:
  port: 8010
spring:
  application:
    name: cake-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}   #註冊到consul的服務名稱

    
zuul:
  prefix: /v1
  routes:
    ribbon:
      path: /ribbon/**
      serviceId: cake-consumer  # 转发到消费者 /ribbon/
    feign:
      path: /feign/**
      serviceId: cake-consumer  # 转发到消费者 /feign/